export interface ThemeInfo {
    id: string
    name: string
    description: string
    colors: {
        background: string
        foreground: string
    }
    author: string
    keywords: string[]
    blogTitle: string
    projectsTitle: string
    blogLabel: string
    projectsLabel: string
    footerEmojis: string
    license: string
}

export const themes: ThemeInfo[] = [
    {
        id: 'default',
        name: 'Jack - Default',
        description: 'Minimal dark theme with clean design',
        colors: {
            background: '#000000',
            foreground: '#ffffff',
        },
        author: 'Jack',
        keywords: ['minimal', 'dark', 'clean'],
        blogTitle: 'Blog',
        projectsTitle: 'Projects',
        blogLabel: 'Blog',
        projectsLabel: 'Projects',
        footerEmojis: '✨💖💫',
        license: 'MIT',
    },
    {
        id: 'wizzard',
        name: 'Zephyr - Cosmic Wizard',
        description: 'Cosmic space theme with purple and indigo colors',
        colors: {
            background: '#0a0e27',
            foreground: '#e0e7ff',
        },
        author: 'Zephyr Stardust',
        keywords: ['cosmic', 'space', 'synthwave'],
        blogTitle: 'Cosmic Thoughts',
        projectsTitle: 'Galactic Creations',
        blogLabel: 'Thoughts',
        projectsLabel: 'Creations',
        footerEmojis: '🌌✨🚀💫👽',
        license: 'WTFPL',
    },
    {
        id: 'beach',
        name: 'Rio - Beach Coder',
        description: 'Tropical beach theme with golden sunset colors',
        colors: {
            background: '#0f172a',
            foreground: '#fef3c7',
        },
        author: 'Rio Tropical',
        keywords: ['beach', 'tropical', 'sunset'],
        blogTitle: 'Beach Stories',
        projectsTitle: 'Island Builds',
        blogLabel: 'Stories',
        projectsLabel: 'Builds',
        footerEmojis: '🏖️🌴☀️🌊🥥',
        license: 'MIT',
    },
    {
        id: 'oldschool',
        name: 'Vic - Retro Coder',
        description: 'Classic retro terminal with green phosphor on black',
        colors: {
            background: '#000000',
            foreground: '#00ff00',
        },
        author: 'Vic Classic',
        keywords: ['retro', 'terminal', 'classic'],
        blogTitle: 'Terminal Archive',
        projectsTitle: 'Classic Programs',
        blogLabel: 'Archive',
        projectsLabel: 'Programs',
        footerEmojis: '💾🖥️⌨️📟💿',
        license: 'BSD',
    },
    {
        id: 'scholar',
        name: 'Luna - Midnight Scholar',
        description: 'Dark academia theme with antique gold on charcoal',
        colors: {
            background: '#1a1a1a',
            foreground: '#d4af37',
        },
        author: 'Luna Nocturne',
        keywords: ['academia', 'scholarly', 'gothic'],
        blogTitle: 'Ancient Tomes',
        projectsTitle: 'Arcane Spells',
        blogLabel: 'Tomes',
        projectsLabel: 'Spells',
        footerEmojis: '📜🕯️🌙📚🦉',
        license: 'AGPL-3.0',
    },
    {
        id: 'neon',
        name: 'Neon - Cyberpunk Dev',
        description: 'Cyberpunk theme with vibrant magenta neon colors',
        colors: {
            background: '#0a0a0f',
            foreground: '#ff00ff',
        },
        author: 'Neon Cyber',
        keywords: ['cyberpunk', 'neon', 'hacking'],
        blogTitle: 'Neon Logs',
        projectsTitle: 'Cyber Scripts',
        blogLabel: 'Hacks',
        projectsLabel: 'Scripts',
        footerEmojis: '💜⚡🌃🔮💎',
        license: 'MIT',
    },
    {
        id: 'forest',
        name: 'Sage - Nature Coder',
        description: 'Nature theme with light green on dark forest background',
        colors: {
            background: '#0d1b0f',
            foreground: '#90ee90',
        },
        author: 'Sage Green',
        keywords: ['nature', 'sustainable', 'eco-friendly'],
        blogTitle: 'Forest Notes',
        projectsTitle: 'Nature Projects',
        blogLabel: 'Leaves',
        projectsLabel: 'Seeds',
        footerEmojis: '🌿🌲🍃🌱🌳',
        license: 'MIT',
    },
    {
        id: 'sunset',
        name: 'Aurora - Sunset Coder',
        description: 'Sunset theme with warm orange on dark background',
        colors: {
            background: '#1a0f0f',
            foreground: '#ff8c42',
        },
        author: 'Aurora Sunset',
        keywords: ['sunset', 'golden hour', 'warm'],
        blogTitle: 'Golden Hour',
        projectsTitle: 'Sunset Builds',
        blogLabel: 'Sunset',
        projectsLabel: 'Horizon',
        footerEmojis: '🌅🌇🌆🌄☀️',
        license: 'MIT',
    },
    {
        id: 'ocean',
        name: 'Coral - Ocean Dev',
        description: 'Ocean theme with cyan blue on deep sea background',
        colors: {
            background: '#0a1a2e',
            foreground: '#00d4ff',
        },
        author: 'Coral Reef',
        keywords: ['ocean', 'aquatic', 'deep blue'],
        blogTitle: 'Ocean Depths',
        projectsTitle: 'Coral Reefs',
        blogLabel: 'Waves',
        projectsLabel: 'Reefs',
        footerEmojis: '🌊🐠🐙🌊💙',
        license: 'MIT',
    },
    {
        id: 'lavender',
        name: 'Lavender - Dreamy Dev',
        description: 'Dreamy pastel theme with lavender purple on dark background',
        colors: {
            background: '#1a1625',
            foreground: '#e6d3ff',
        },
        author: 'Lavender Dream',
        keywords: ['pastel', 'dreamy', 'soft'],
        blogTitle: 'Dreamy Thoughts',
        projectsTitle: 'Pastel Projects',
        blogLabel: 'Dreams',
        projectsLabel: 'Clouds',
        footerEmojis: '💜☁️🌸✨🦄',
        license: 'MIT',
    },
    {
        id: 'fire',
        name: 'Blaze - Fire Coder',
        description: 'Fiery theme with orange-red on dark background',
        colors: {
            background: '#1a0a0a',
            foreground: '#ff4500',
        },
        author: 'Blaze Fire',
        keywords: ['fire', 'passion', 'intense'],
        blogTitle: 'Fire Logs',
        projectsTitle: 'Fire Projects',
        blogLabel: 'Flames',
        projectsLabel: 'Embers',
        footerEmojis: '🔥💥🌋⚡🔥',
        license: 'MIT',
    },
    {
        id: 'ice',
        name: 'Frost - Ice Dev',
        description: 'Ice theme with powder blue on dark background',
        colors: {
            background: '#0a1419',
            foreground: '#b0e0e6',
        },
        author: 'Frost Ice',
        keywords: ['ice', 'frost', 'cool'],
        blogTitle: 'Frozen Thoughts',
        projectsTitle: 'Ice Projects',
        blogLabel: 'Ice',
        projectsLabel: 'Snow',
        footerEmojis: '❄️🧊🌨️💎❄️',
        license: 'MIT',
    },
    {
        id: 'matrix',
        name: 'Neo - Matrix Coder',
        description: 'Matrix theme with green code on black background',
        colors: {
            background: '#000000',
            foreground: '#00ff41',
        },
        author: 'Neo Matrix',
        keywords: ['matrix', 'digital reality', 'code'],
        blogTitle: 'The Matrix',
        projectsTitle: 'Matrix Code',
        blogLabel: 'Code',
        projectsLabel: 'Matrix',
        footerEmojis: '💚⚡🔮🌐💻',
        license: 'MIT',
    },
    {
        id: 'candy',
        name: 'Candy - Sweet Dev',
        description: 'Sweet theme with hot pink on dark background',
        colors: {
            background: '#1a0f1a',
            foreground: '#ff69b4',
        },
        author: 'Candy Sweet',
        keywords: ['sweet', 'candy', 'colorful'],
        blogTitle: 'Sweet Blog',
        projectsTitle: 'Sweet Projects',
        blogLabel: 'Sweets',
        projectsLabel: 'Treats',
        footerEmojis: '🍬🍭🍰🍩🍪',
        license: 'MIT',
    },
    {
        id: 'midnight',
        name: 'Midnight - Night Coder',
        description: 'Midnight theme with deep purple on black background',
        colors: {
            background: '#000000',
            foreground: '#8b00ff',
        },
        author: 'Midnight Dark',
        keywords: ['midnight', 'night', 'dark'],
        blogTitle: 'Midnight Thoughts',
        projectsTitle: 'Dark Projects',
        blogLabel: 'Night',
        projectsLabel: 'Dark',
        footerEmojis: '🌙⭐🌃🌌🌑',
        license: 'MIT',
    },
    {
        id: 'rainbow',
        name: 'Rainbow - Colorful Dev',
        description: 'Rainbow theme with white on black background',
        colors: {
            background: '#0a0a0a',
            foreground: '#ffffff',
        },
        author: 'Rainbow Spectrum',
        keywords: ['rainbow', 'colorful', 'vibrant'],
        blogTitle: 'Colorful Thoughts',
        projectsTitle: 'Rainbow Projects',
        blogLabel: 'Colors',
        projectsLabel: 'Spectrum',
        footerEmojis: '🌈🎨✨💫🎭',
        license: 'MIT',
    },
    {
        id: 'steampunk',
        name: 'Steam - Steampunk Engineer',
        description: 'Steampunk theme with brass gold on dark brown background',
        colors: {
            background: '#1a0f0a',
            foreground: '#d4a574',
        },
        author: 'Steam Engineer',
        keywords: ['steampunk', 'engineering', 'mechanical'],
        blogTitle: 'Brass Journals',
        projectsTitle: 'Mechanical Works',
        blogLabel: 'Gears',
        projectsLabel: 'Machines',
        footerEmojis: '⚙️🔧🛠️⚡🔩',
        license: 'MIT',
    },
    {
        id: 'aurora',
        name: 'Aurora - Northern Lights Dev',
        description: 'Aurora theme with cyan turquoise on dark blue background',
        colors: {
            background: '#0a1419',
            foreground: '#00ffd4',
        },
        author: 'Aurora Borealis',
        keywords: ['aurora', 'northern lights', 'arctic'],
        blogTitle: 'Northern Lights',
        projectsTitle: 'Aurora Projects',
        blogLabel: 'Lights',
        projectsLabel: 'Stars',
        footerEmojis: '🌌✨🌠💫⭐',
        license: 'MIT',
    },
]
